#!/usr/bin/env bash
# Reads the current tool change progress from JSON and prints it.
set -euo pipefail

# Helper functions
error() {
    echo "$*" >&2
}

# Resolve the real user when running under sudo
get_real_user() {
    if [ -n "${SUDO_USER:-}" ]; then
        echo "$SUDO_USER"
    else
        echo "${USER:-$(whoami)}"
    fi
}

# Get the home directory of the real user
get_real_home() {
    local real_user
    real_user=$(get_real_user)
    if [ -n "${SUDO_USER:-}" ]; then
        getent passwd "$real_user" | cut -d: -f6
    else
        echo "${HOME:-$(eval echo ~"$real_user")}"
    fi
}

# Resolve PRINTER_CONFIG_DIR
resolve_printer_config_dir() {
    # Priority 1: Environment variable
    if [ -n "${PRINTER_CONFIG_DIR:-}" ] && [ -d "$PRINTER_CONFIG_DIR" ]; then
        echo "$PRINTER_CONFIG_DIR"
        return 0
    fi
    
    # Priority 2: Check for .toolchange-config
    for dir in "." "${HOME}/printer_data/config"; do
        if [ -f "$dir/.toolchange-config" ]; then
            # shellcheck disable=SC1090
            if source "$dir/.toolchange-config" 2>/dev/null && [ -n "${PRINTER_CONFIG_DIR:-}" ]; then
                echo "$PRINTER_CONFIG_DIR"
                return 0
            fi
        fi
    done
    
    # Priority 3: Auto-scan
    local real_home
    real_home=$(get_real_home)
    
    if [ -d "$real_home/printer_data/config" ]; then
        echo "$real_home/printer_data/config"
        return 0
    fi
    
    for dir in "$real_home"/printer*; do
        if [ -d "$dir/printer_data/config" ]; then
            echo "$dir/printer_data/config"
            return 0
        fi
    done
    
    return 1
}

# Write color_prompt.cfg with current tool change info
write_color_prompt_cfg() {
    local config_dir="$1"
    local current_change="$2"
    local total_changes="$3"
    local color="${4:-Unknown}"
    local tool_number="${5:-0}"
    
    local cfg_file="$config_dir/color_prompt.cfg"
    local progress=$((current_change + 1))
    
    # Create the Klipper macro
    cat > "$cfg_file" <<'EOF_MACRO'
# Auto-generated by get_tool_change_status.sh
# This file is overwritten on every status check

[gcode_macro TOOL_CHANGE_STATUS]
description: Display current tool change status
variable_current_change: CURRENT_CHANGE_VAL
variable_total_changes: TOTAL_CHANGES_VAL
variable_progress: PROGRESS_VAL
variable_color: "COLOR_VAL"
gcode:
    {% set status = printer["gcode_macro TOOL_CHANGE_STATUS"] %}
    RESPOND MSG="Tool Change {status.progress} of {status.total_changes}: {status.color} (T{status.tool_number})"
EOF_MACRO
    
    # Replace placeholders
    sed -i "s/CURRENT_CHANGE_VAL/$current_change/g" "$cfg_file"
    sed -i "s/TOTAL_CHANGES_VAL/$total_changes/g" "$cfg_file"
    sed -i "s/PROGRESS_VAL/$progress/g" "$cfg_file"
    sed -i "s/COLOR_VAL/$color/g" "$cfg_file"
    
    # Set ownership if running as sudo
    if [ -n "${SUDO_USER:-}" ]; then
        local real_user
        real_user=$(get_real_user)
        chown "$real_user:$real_user" "$cfg_file" 2>/dev/null || true
    fi
    
    return 0
}

# Main logic
CONFIG_DIR=$(resolve_printer_config_dir) || {
    error "ERROR: Could not detect printer config directory."
    error "Please set PRINTER_CONFIG_DIR or run the installer."
    exit 1
}

JSON_FILE="$CONFIG_DIR/tool_changes.json"

if [ ! -f "$JSON_FILE" ]; then
    error "ERROR: No tool change data found."
    exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
    error "ERROR: jq is required but not installed"
    exit 2
fi

current_change=$(jq '.current_change' "$JSON_FILE")
total_changes=$(jq '.total_changes' "$JSON_FILE")

# Extract the tool number and color for the current change (even if completed)
if [ "$current_change" -lt "$total_changes" ]; then
    tool_number=$(jq ".changes[$current_change].tool_number" "$JSON_FILE")
    color=$(jq -r ".changes[$current_change].color" "$JSON_FILE")
    line=$(jq ".changes[$current_change].line" "$JSON_FILE")
    
    # Always write color_prompt.cfg
    write_color_prompt_cfg "$CONFIG_DIR" "$current_change" "$total_changes" "$color" "$tool_number"
    
    echo "Tool Change $((current_change + 1)) of $total_changes - $color (T$tool_number) at line $line"
else
    # Write completion status to color_prompt.cfg
    write_color_prompt_cfg "$CONFIG_DIR" "$current_change" "$total_changes" "Completed" "0"
    
    echo "Tool changes completed."
fi

